In [1]:
import pandas as pd
import numpy as np
#useful resource: https://stackoverflow.com/questions/28654047/pandas-convert-some-columns-into-rows

In [2]:
cities = pd.read_csv('City_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_mon.csv')
cities

,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,CountyName,1996-01-31,1996-02-29,...,2020-04-30,2020-05-31,2020-06-30,2020-07-31,2020-08-31,2020-09-30,2020-10-31,2020-11-30,2020-12-31,2021-01-31
0,6181,0,New York,City,NY,NY,New York-Newark-Jersey City,Queens County,192871.0,192315.0,...,643475.0,643687.0,645117.0,646066.0,648133.0,650155.0,652505.0,654716.0,656470.0,657637.0
1,12447,1,Los Angeles,City,CA,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,186401.0,186377.0,...,756076.0,758358.0,759820.0,766054.0,774867.0,784871.0,792210.0,798875.0,804452.0,809865.0
2,39051,2,Houston,City,TX,TX,Houston-The Woodlands-Sugar Land,Harris County,92977.0,93091.0,...,191322.0,192289.0,193019.0,193875.0,194884.0,196562.0,198226.0,200351.0,202428.0,204810.0
3,17426,3,Chicago,City,IL,IL,Chicago-Naperville-Elgin,Cook County,136665.0,136511.0,...,261383.0,262100.0,263025.0,264613.0,266502.0,269040.0,271553.0,273691.0,275567.0,276992.0
4,6915,4,San Antonio,City,TX,TX,San Antonio-New Braunfels,Bexar County,95743.0,95709.0,...,190812.0,191315.0,191819.0,192696.0,193812.0,195228.0,196945.0,198743.0,200690.0,202634.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25661,12973,29449,Newcastle,City,NE,NE,Sioux City,Dixon County,NaN,NaN,...,68483.0,68557.0,68663.0,68794.0,68927.0,69000.0,69112.0,69607.0,70280.0,70883.0
25662,29846,29449,Barwick,City,GA,GA,Valdosta,Brooks County,30135.0,30093.0,...,59430.0,59939.0,60361.0,60703.0,61026.0,61518.0,62088.0,62862.0,63422.0,63883.0
25663,51148,29449,Broad Top,City,PA,PA,Huntingdon,Huntingdon County,NaN,NaN,...,107498.0,107834.0,108146.0,108717.0,109341.0,109814.0,110869.0,112155.0,113642.0,114821.0
25664,232332,29449,Cool,City,TX,TX,Dallas-Fort Worth-Arlington,Parker County,NaN,NaN,...,230318.0,231437.0,231753.0,230706.0,229281.0,228344.0,227479.0,228141.0,227251.0,226137.0
25665,5133,29449,Hermitage,City,MO,MO,NaN,Hickory County,NaN,NaN,...,98932.0,98655.0,98671.0,98819.0,99135.0,99555.0,100376.0,101250.0,102192.0,102930.0

In [18]:
dates = cities.columns[8:]
dates

Index(['1996-01-31', '1996-02-29', '1996-03-31', '1996-04-30', '1996-05-31',
       '1996-06-30', '1996-07-31', '1996-08-31', '1996-09-30', '1996-10-31',
       ...
       '2020-04-30', '2020-05-31', '2020-06-30', '2020-07-31', '2020-08-31',
       '2020-09-30', '2020-10-31', '2020-11-30', '2020-12-31', '2021-01-31'],
      dtype='object', length=301)

In [23]:
clean_cities = cities.melt(id_vars=cities.columns[0:8], 
        var_name="Date", 
        value_name="Value")

In [30]:
clean_cities.sort_values(['RegionID','Date'],inplace=True)

In [31]:
clean_cities

,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,CountyName,Date,Value
9915,3300,10860,Aberdeen,City,ID,ID,Blackfoot,Bingham County,1996-01-31,NaN
35581,3300,10860,Aberdeen,City,ID,ID,Blackfoot,Bingham County,1996-02-29,NaN
61247,3300,10860,Aberdeen,City,ID,ID,Blackfoot,Bingham County,1996-03-31,NaN
86913,3300,10860,Aberdeen,City,ID,ID,Blackfoot,Bingham County,1996-04-30,NaN
112579,3300,10860,Aberdeen,City,ID,ID,Blackfoot,Bingham County,1996-05-31,NaN
...,...,...,...,...,...,...,...,...,...,...
7603291,760887,6571,Berlin,City,NJ,NJ,Philadelphia-Camden-Wilmington,Camden County,2020-09-30,228877.0
7628957,760887,6571,Berlin,City,NJ,NJ,Philadelphia-Camden-Wilmington,Camden County,2020-10-31,232242.0
7654623,760887,6571,Berlin,City,NJ,NJ,Philadelphia-Camden-Wilmington,Camden County,2020-11-30,235545.0
7680289,760887,6571,Berlin,City,NJ,NJ,Philadelphia-Camden-Wilmington,Camden County,2020-12-31,238584.0
7705955,760887,6571,Berlin,City,NJ,NJ,Philadelphia-Camden-Wilmington,Camden County,2021-01-31,242582.0

In [33]:
clean_cities[clean_cities['Value'].isna()]['RegionName'].value_counts()

Franklin      2318
Greenville    2070
Ashland       1870
Florence      1818
Jackson       1766
              ...
Weirsdale        1
Redvale          1
Olcott           1
Maribel          1
Vine Grove       1
Name: RegionName, Length: 11149, dtype: int64

In [28]:
clean_cities.to_csv('Zillow City Data.csv')